name: Release

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is needed for correctly determining next release with semantic release
          fetch-depth: 0
          persist-credentials: false

      - name: Semantic release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23
          extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release/git@10
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release page
        if: steps.semantic.outputs.new_release_published == 'true'
        run: echo "publish"